### ISSUE TITLE
temporarily set pool via GET argument

### ISSUE THREAD

**Issue by incertia** [DaFluffyPotato/hitbloq#10]
very UX thing but if someone clicks a map from pool A's maplist but currently has pool B selected, the ratings from pool B are used rather than pool A.

probably not too hard with a GET argument and defaulting to the currently selected pool if none was found

**Comment by DaFluffyPotato** [comment]
I won't do it like that. It definitely makes more sense when you first click a song within a pool, but if you click someone's profile from there, it gets even more confusing since it switches on you after showing a leaderboard from the pool you first looked at. I might change it so going to _any_ map pool will automatically switch you set pool to the map pool you're looking at.
